#!/usr/bin/env node
'use strict';

const axios = require('axios');
const queryString = require('querystring');

// Fill out this Bitbucket credentials
const BB_USERNAME = '';
const BB_PASSWORD = '';
const REPO_OWNER = '';
const REPO_SLUG = '';

const pipelinesCacheEndpoint = `https://api.bitbucket.org/internal/repositories/${REPO_OWNER}/${REPO_SLUG}/pipelines_caches/`;

(async () => {
  const axiosConfig = {
    auth: {
      username: BB_USERNAME,
      password: BB_PASSWORD,
    },
  };
  try {
    console.log('Checking for existing caches');
    const response = await axios.get(pipelinesCacheEndpoint, axiosConfig);
    if (
      !response.data ||
      !response.data.values ||
      !response.data.values.length > 0
    ) {
      console.log('No caches found. Exiting.');
      return;
    }
    console.log(JSON.stringify(response.data, null, 2));
    //return;

    // Just in case we ever use a second cache, we'll explicitly look for a node cache
    //const nodeCache = response.data.values.find(cache => cache.name === "node");

    //console.log(`Deleting cache "${cacheUuid}"`);
    await Promise.all(
      response.data.values.map(cache => {
        const deleteEndpoint = `${pipelinesCacheEndpoint}${queryString.escape(
          cache.uuid,
        )}`;
        console.log(`Clearing cache for ${cache.name} - ${cache.path}`);
        return axios.delete(deleteEndpoint, axiosConfig);
      }),
    );
  } catch (e) {
    // The actual request to delete the cache will return a 500 error... That's what we get for
    // relying on internal api's.... we'll ignore it if we see it
    if (e.message !== 'Request failed with status code 500') {
      console.log(e);
      console.error('Error fetching or deleting cache: ', e.message);
      process.exit(1);
    } else {
      console.log('Success!');
    }
  }
})();
